/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taiwanmap;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class ReadFilePanel extends javax.swing.JPanel {
    private Aises aises;
    DateFormat sdff = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");
    /**
     * Creates new form ReadFilePanel
     */
    public ReadFilePanel() {
        initComponents();
    }
    public void readFile (String fileName) {
        fileNameLabel.setText(fileName);
        aises = new Aises(fileName);
        Date beginDate = aises.getBeginDate();
        Date endDate = aises.getEndDate();
        double maxLat = aises.getMaxLat();
        double minLat = aises.getMinLat();
        double maxLng = aises.getMaxLng();
        double minLng = aises.getMinLng();
        
        beginDateLabel.setText(sdff.format(beginDate));
        endDateLabel.setText(sdff.format(endDate));
        maxLatLabel.setText(" N:" + String.format("%.2f", maxLat));
        minLatLabel.setText(" N:" + String.format("%.2f", minLat));
        maxLngLabel.setText(" E:" + String.format("%.2f", maxLng));
        minLngLabel.setText(" E:" + String.format("%.2f", minLng));
    }
    public Aises getAises() {
        return aises;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        beginDateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maxLatLabel = new javax.swing.JLabel();
        maxLngLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        minLatLabel = new javax.swing.JLabel();
        minLngLabel = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel3.setText("分析檔案：");

        fileNameLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        fileNameLabel.setText("a.csv");
        fileNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel1.setText("開始時間：");

        beginDateLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        beginDateLabel.setText("2016.04.08 12:40:00");
        beginDateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel4.setText("最高座標：");

        maxLatLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        maxLatLabel.setText("N:27.10");
        maxLatLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        maxLngLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        maxLngLabel.setText("E:122.10");
        maxLngLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel2.setText("結束時間：");

        endDateLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        endDateLabel.setText("2016.05.14 18:05:00");
        endDateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel5.setText("最低座標：");

        minLatLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        minLatLabel.setText("N:25.20");
        minLatLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        minLngLabel.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        minLngLabel.setText("E:120.10");
        minLngLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(beginDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minLatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxLatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxLngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minLngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameLabel)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(beginDateLabel)
                    .addComponent(jLabel4)
                    .addComponent(maxLatLabel)
                    .addComponent(maxLngLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(endDateLabel)
                    .addComponent(jLabel5)
                    .addComponent(minLatLabel)
                    .addComponent(minLngLabel))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beginDateLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel maxLatLabel;
    private javax.swing.JLabel maxLngLabel;
    private javax.swing.JLabel minLatLabel;
    private javax.swing.JLabel minLngLabel;
    // End of variables declaration//GEN-END:variables
}
